define({
    outputUnit: "é_Output Unit_È",
    wkid: "é_Output WKID_È",
    label: "é_Output Label_È",
    transformationWkid: 'é_Transformation WKID_È',
    transformationLabel: 'é_Transformation Label_È',
    transformForward: 'é_Transform Forward_È',
    actions: "é_Actions_È",
    warning: "é_please input valid spatial reference WKID!_È",
    tfWarning: "é_please input valid datum transformation WKID!_È",
    spinnerLabel: "é_Round coordinate to:_È ",
    decimalPlace: "é_decimal places_È",
    separator: "é_Show thousand separators_È",

    add: "é_Add Output Coordinate System_È",
    edit: "é_Edit Coordinate System_È",
    output: "é_Output Coordinate System_È",
    cName: "é_Coordinate system name_È",
    units: "é_Display Units:_È ",
    datum: "é_Datum Transformation_È",
    tName: "é_Transformation name_È",
    forward: "é_Use transformation forward_È",
    ok: "é_OK_È",
    cancel: 'é_Cancel_È',
    REPEATING_ERROR: "é_The fllowing fields are repeated:_È "
});