define({
    outputUnit: "Ă_Output Unit_ș",
    wkid: "Ă_Output WKID_ș",
    label: "Ă_Output Label_ș",
    transformationWkid: 'Ă_Transformation WKID_ș',
    transformationLabel: 'Ă_Transformation Label_ș',
    transformForward: 'Ă_Transform Forward_ș',
    actions: "Ă_Actions_ș",
    warning: "Ă_please input valid spatial reference WKID!_ș",
    tfWarning: "Ă_please input valid datum transformation WKID!_ș",
    spinnerLabel: "Ă_Round coordinate to:_ș ",
    decimalPlace: "Ă_decimal places_ș",
    separator: "Ă_Show thousand separators_ș",

    add: "Ă_Add Output Coordinate System_ș",
    edit: "Ă_Edit Coordinate System_ș",
    output: "Ă_Output Coordinate System_ș",
    cName: "Ă_Coordinate system name_ș",
    units: "Ă_Display Units:_ș ",
    datum: "Ă_Datum Transformation_ș",
    tName: "Ă_Transformation name_ș",
    forward: "Ă_Use transformation forward_ș",
    ok: "Ă_OK_ș",
    cancel: 'Ă_Cancel_ș',
    REPEATING_ERROR: "Ă_The fllowing fields are repeated:_ș "
});