define({
    outputUnit: "ķ_Output Unit_ū",
    wkid: "ķ_Output WKID_ū",
    label: "ķ_Output Label_ū",
    transformationWkid: 'ķ_Transformation WKID_ū',
    transformationLabel: 'ķ_Transformation Label_ū',
    transformForward: 'ķ_Transform Forward_ū',
    actions: "ķ_Actions_ū",
    warning: "ķ_please input valid spatial reference WKID!_ū",
    tfWarning: "ķ_please input valid datum transformation WKID!_ū",
    spinnerLabel: "ķ_Round coordinate to:_ū ",
    decimalPlace: "ķ_decimal places_ū",
    separator: "ķ_Show thousand separators_ū",

    add: "ķ_Add Output Coordinate System_ū",
    edit: "ķ_Edit Coordinate System_ū",
    output: "ķ_Output Coordinate System_ū",
    cName: "ķ_Coordinate system name_ū",
    units: "ķ_Display Units:_ū ",
    datum: "ķ_Datum Transformation_ū",
    tName: "ķ_Transformation name_ū",
    forward: "ķ_Use transformation forward_ū",
    ok: "ķ_OK_ū",
    cancel: 'ķ_Cancel_ū',
    REPEATING_ERROR: "ķ_The fllowing fields are repeated:_ū "
});