define({
  root: {
    placeholder: "Placeholder Text",
    url: "Geocoder URL",
    name: "Geocoder Name",
    singleLineFieldName: "SingleLineFieldName",
    portalConnectionError: 'Can not get the configurations of geocoder from portal',
    actions: "Actions",
    warning: "Incorrect Service",
    instruction: "Establish the geocoders that will be used in this widget. Click Add Geocoder to reference a URL, specify a user friendly name, and set other properties. " +
    "You can also reorder, configure, or delete your geocoders below.",
    add: "Add Geocoder",
    edit: "Edit Geocoder",
    ok: "OK",
    cancel: "Cancel",
    REPEATING_ERROR: "The following fields are repeated: "
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});