define({
  root: {
    welcomeMessage: "Sandy McTire's Canadian Geography Challenge",
    licenceAgree: "I agree to",
    licenceTerm: "ArcGIS Web Application Terms",
    labelContinue: "Continue",
    instructions:"Sandy McTire wants to give you a cash bonus! Sandy recently discovered a stack of McTires piling up in his kitchen drawer and is giving you a chance to claim them. All he asks is that you answer as many questions as you can relating to Canadian geography. Based on the question given, select a point on the map to indicate your guess. You can continue playing until you run out of McTires.",
    errorString: "* You need to agree to the licence to continue."
  },
  "ar": true,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": true,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-BR": true,
  "pt-PT": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});