define({
  root: {
    routeUrl:"Route URL",
    locatorUrl:"Geocoder URL",
    geocoderOptions:"Geocoder options",
    autoComplete:"Auto complete",
    maxLocations:"Max locations",
    minCharacters:"Min characters",
    searchDelay:"Search delay",
    placeholder:"Placeholder",
    routeOptions:"Route options",
    directionsLanguage:"Directions language",
    directionsLengthUnits:"Directions length units",
    directionsOutputType:"Directions output type",
    impedanceAttribute:"Impedance attribute",
    kilometers: 'Kilometers',
    miles: 'Miles',
    meters: 'Meters',
    feet: 'Feet',
    yards: 'Yards',
    nauticalMiles:'Nautical Miles'
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});