define({
  root: {
    state: "By default, coordinates will display in current map’s coordinate system. " +
    "To get coordinates in other coordinate systems, you need to additionally add them and specify appropriate transformations.",
    outputUnit: "Output Unit",
    wkid: "Output WKID",
    label: "Output Coordinate System Name",
    transformationWkid: 'Transformation WKID',
    transformationLabel: 'Transformation Label',
    transformForward: 'Transform Forward',
    actions: "Actions",
    warning: "Please input valid spatial reference WKID!",
    tfWarning: "Please input valid datum transformation WKID!",
    spinnerLabel: "Round coordinates to: ",
    decimalPlace: "decimal places",
    separator: "Show thousand separators",
    getVersionError: "Can't get the version of Geometry Service",

    add: "Add Output Coordinate System",
    edit: "Edit Coordinate System",
    output: "Output Coordinate System",
    cName: "Coordinate System Name",
    units: "Display Units: ",
    datum: "Datum Transformation",
    tName: "Transformation Name",
    forward: "Use transformation forward",
    ok: "OK",
    cancel: 'Cancel',
    olderVersion: "The Geometry Service doesn't support transforming operation",
    REPEATING_ERROR: " Coordinate system exists in the output list."
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});