define({
    outputUnit: "ä_Output Unit_Ü",
    wkid: "ä_Output WKID_Ü",
    label: "ä_Output Label_Ü",
    transformationWkid: 'ä_Transformation WKID_Ü',
    transformationLabel: 'ä_Transformation Label_Ü',
    transformForward: 'ä_Transform Forward_Ü',
    actions: "ä_Actions_Ü",
    warning: "ä_please input valid spatial reference WKID!_Ü",
    tfWarning: "ä_please input valid datum transformation WKID!_Ü",
    spinnerLabel: "ä_Round coordinate to:_Ü ",
    decimalPlace: "ä_decimal places_Ü",
    separator: "ä_Show thousand separators_Ü",

    add: "ä_Add Output Coordinate System_Ü",
    edit: "ä_Edit Coordinate System_Ü",
    output: "ä_Output Coordinate System_Ü",
    cName: "ä_Coordinate system name_Ü",
    units: "ä_Display Units:_Ü ",
    datum: "ä_Datum Transformation_Ü",
    tName: "ä_Transformation name_Ü",
    forward: "ä_Use transformation forward_Ü",
    ok: "ä_OK_Ü",
    cancel: 'ä_Cancel_Ü',
    REPEATING_ERROR: "ä_The fllowing fields are repeated:_Ü "
});