define({
  root: {
    hintMessage: "Click the map to get coordinates",
    defaultLabel: "Default Settings",
    realtimeLabel: "Move mouse to get coordinates",
    computing: "Computing...",
    latitudeLabel: "Latitude",
    longitudeLabel: "Longitude"
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});