define({
    routeUrl:"网络分析服务URL",
    locatorUrl:"地理编码服务URL",
    geocoderOptions:"地理编码选项",
    autoComplete:"自动完成",
    maxLocations:"最大地址数",
    minCharacters:"最小字符数",
    searchDelay:"搜索延迟",
    placeholder:"占位符",
    routeOptions:"网络分析选项",
    directionsLanguage:"路书语言",
    directionsLengthUnits:"路书长度单位",
    directionsOutputType:"路书输出类型",
    impedanceAttribute:"阻抗属性",
    kilometers: '千米',
    miles: '英里',
    meters: '米',
    feet: '英尺',
    yards: '码',
    nauticalMiles:'海里'
  });