define({
    outputUnit: "한_Output Unit_빠",
    wkid: "한_Output WKID_빠",
    label: "한_Output Label_빠",
    transformationWkid: '한_Transformation WKID_빠',
    transformationLabel: '한_Transformation Label_빠',
    transformForward: '한_Transform Forward_빠',
    actions: "한_Actions_빠",
    warning: "한_please input valid spatial reference WKID!_빠",
    tfWarning: "한_please input valid datum transformation WKID!_빠",
    spinnerLabel: "한_Round coordinate to:_빠 ",
    decimalPlace: "한_decimal places_빠",
    separator: "한_Show thousand separators_빠",

    add: "한_Add Output Coordinate System_빠",
    edit: "한_Edit Coordinate System_빠",
    output: "한_Output Coordinate System_빠",
    cName: "한_Coordinate system name_빠",
    units: "한_Display Units:_빠 ",
    datum: "한_Datum Transformation_빠",
    tName: "한_Transformation name_빠",
    forward: "한_Use transformation forward_빠",
    ok: "한_OK_빠",
    cancel: '한_Cancel_빠',
    REPEATING_ERROR: "한_The fllowing fields are repeated:_빠 "
});